### ISSUE TITLE
Get the status 500 when login

### ISSUE THREAD

**Issue by knew-cht** [OpenCSGs/csghub-installer#314]
**Describe the bug**
When trying to login, the browser return error 500.

**To Reproduce**
1. deploy csghub using the following `docker-compose.yaml`
```yaml
services:
  csghub:
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/omnibus-csghub:v1.8.0-ce
    hostname: 'csghub.example.com'
    environment:
      CSGHUB_OMNIBUS_CONFIG: |
        csghub:
          external_url: "http://10.144.0.1" # 访问 CSGHub 实例域名，建议使用域名方式配置
        runner:
          enable: false                                      # 是否启用 Runner 服务，禁用则仅能使用基础功能
          deploy:
            knative:
              services:
                - type: "NodePort"        # 如果 Kubernetes 集群支持 LoadBalancer，可以使用 LoadBalancer
                  domain: "app.internal"    # 自定义 Knative Serving 内部域名
                  host: "192.168.18.10"   # 暴露 kourier 服务的 EXTERNAL-IP
                  port: 30123                           # 自定义端口号，type=LoadBalancer, 请指定为 80
    ports:
      - '80:80'                 # Nginx
      - '2222:2222'     # Git Over SSH
      - '5000:5000'     # Container Registry
      - '8000:8000'     # Casdoor
      - '9000:9000'     # Minio
    volumes:
      - ./csghub/etc:/etc/csghub
      - ./csghub/logs:/var/log/csghub
      - ./csghub/data:/var/opt/csghub
      - ./csghub/.kube:/etc/csghub/.kube
    restart: always
    shm_size: '256m'
```
2. `docker compose up -d && docker compose ps`
3.  `docker compose ps && docker exec -it <container> bash `
4.  `cat /etc/csghub/init_root_password`
5.  In the webui, using root/pssword to login

**Expected behavior**
Login sucesses.

**Desktop (please complete the following information):**
 - OS: Ubuntu24.04.01
 - Browser: firefox
 - Version: 131.0

**Additional context**
`$ csghub-ctl status ` shows:

```accsesslog
run: accounting: (pid 2140) 8286s; run: log: (pid 1246) 8288s
run: casdoor: (pid 2272) 8285s; run: log: (pid 1244) 8288s
run: dataviewer: (pid 2451) 8284s; run: log: (pid 1239) 8288s
run: dnsmasq: (pid 1272) 8288s; run: log: (pid 1266) 8288s
run: gitaly: (pid 432275) 1s; run: log: (pid 1274) 8288s
run: gitlab_shell: (pid 1255) 8288s; run: log: (pid 1245) 8288s
run: minio: (pid 1260) 8288s; run: log: (pid 1252) 8288s
run: mirror_lfs: (pid 1668) 8287s; run: log: (pid 1265) 8288s
run: mirror_repo: (pid 2450) 8284s; run: log: (pid 1258) 8288s
run: nats: (pid 1273) 8288s; run: log: (pid 1268) 8288s
run: nginx: (pid 1269) 8288s; run: log: (pid 1261) 8288s
down: notification: 0s, normally up, want up; run: log: (pid 1292) 8288s
run: portal: (pid 1582) 8287s; run: log: (pid 1293) 8288s
run: postgresql: (pid 1270) 8288s; run: log: (pid 1263) 8288s
run: redis: (pid 1277) 8288s; run: log: (pid 1276) 8288s
run: registry: (pid 1253) 8288s; run: log: (pid 1242) 8288s
run: rproxy: (pid 2569) 8284s; run: log: (pid 1259) 8288s
run: server: (pid 2498) 8284s; run: log: (pid 1240) 8288s
run: temporal: (pid 1719) 8287s; run: log: (pid 1256) 8288s
run: user: (pid 2660) 8284s; run: log: (pid 1280) 8288s
```

`/var/log/csghub/casdoor/current` shows:

```accesslog
2025-06-25_08:12:33.93292 subOwner = anonymous, subName = anonymous, method = POST, urlPath = /api/login, obj.Owner = , obj.Name = , result = allow
2025-06-25_08:12:33.93294 2025/06/25 08:12:33.932 [I]  (x.x.x.x) subOwner = anonymous, subName = anonymous, method = POST, urlPath = /api/login, obj.Owner = , obj.Name = , result = allow
```

---
`/var/log/csghub/server/current` shows:

```accesslog
2025-06-25_08:13:04.49721 {"time":"2025-06-25T08:13:04.497142394Z","level":"INFO","msg":"http request","ip":"x.x.x.x","method":"GET","latency(ms)":30001,"status":500,"current_user":"","auth_type":"","url":"/api/v1/callback/casdoor?code=b91e5868c00b5fd10fb0&state=casdoor","full_path":"/api/v1/callback/casdoor"}
```
---
`/var/log/csghub/nginx/current` shows:

```accesslog
2025-06-25_08:12:34.04723 {"remote_addr":"x.x.x.x","remote_user":"","time_local":"25/Jun/2025:08:12:34 +0000","request":"POST /api/login?clientId=7a97bc5168cb75ffc514&responseType=code&redirectUri=http%3A%2F%2F10.144.0.1%2Fapi%2Fv1%2Fcallback%2Fcasdoor&type=code&scope=read&state=casdoor&nonce=&code_challenge_method=&code_challenge= HTTP/1.1","status":"200","body_bytes_sent":"87","http_referer":"http://10.144.0.1:8000/login/oauth/authorize?client_id=7a97bc5168cb75ffc514&response_type=code&redirect_uri=http://10.144.0.1/api/v1/callback/casdoor&scope=read&state=casdoor","http_user_agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0","http_x_forwarded_for":"","upstream_addr":"127.0.0.1:8087","upstream_status":"200","request_time":0.116,"upstream_response_time":0.116,"host":"10.144.0.1"}
2025-06-25_08:13:04.49736 2025/06/25 08:13:04 [error] 1757#1757: *107 upstream prematurely closed connection while reading upstream, client: x.x.x.x, server: 10.144.0.1, request: "GET /api/v1/callback/casdoor?code=b91e5868c00b5fd10fb0&state=casdoor HTTP/1.1", upstream: "http://127.0.0.1:8080/api/v1/callback/casdoor?code=b91e5868c00b5fd10fb0&state=casdoor", host: "10.144.0.1", referrer: "http://10.144.0.1:8000/"
2025-06-25_08:13:04.49746 {"remote_addr":"x.x.x.x","remote_user":"","time_local":"25/Jun/2025:08:13:04 +0000","request":"GET /api/v1/callback/casdoor?code=b91e5868c00b5fd10fb0&state=casdoor HTTP/1.1","status":"500","body_bytes_sent":"85","http_referer":"http://10.144.0.1:8000/","http_user_agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0","http_x_forwarded_for":"","upstream_addr":"127.0.0.1:8080","upstream_status":"500","request_time":30.002,"upstream_response_time":30.002,"host":"10.144.0.1"}
```
---

`/var/log/csghub/user/current` shows:

```accesslog
2025-06-25_08:13:04.49681 {"time":"2025-06-25T08:13:04.496739127Z","level":"ERROR","msg":"Failed to signin","error":"failed to get token from casdoor,error:Post \"http://10.144.0.1:8000/api/login/oauth/access_token\": dial tcp 10.144.0.1:8000: i/o timeout","code":"b91e5868c00b5fd10fb0","state":"casdoor"}
2025-06-25_08:13:04.49684 {"time":"2025-06-25T08:13:04.496812745Z","level":"INFO","msg":"http request","ip":"x.x.x.x","method":"GET","latency(ms)":30000,"status":500,"current_user":"","auth_type":"","url":"/api/v1/callback/casdoor?code=b91e5868c00b5fd10fb0&state=casdoor","full_path":"/api/v1/callback/casdoor"}
```

自行註冊新帳號，再嘗試登入也是相同狀況
